#!/bin/bash

exec 2>&1

if [ "${P_PAC_FLAG}" == "true" ]; then
    if [ "${SS_MODULE}" == "ss-local" ]; then
        echo "starting privoxy pac..."
        if [ -n "${P_SOCKS_PROXY}" ]; then
            sed -i 's/127.0.0.1:1080/${P_SOCKS_PROXY}/g' /etc/privoxy/gfwlist.action
        fi
	    privoxy /etc/privoxy/config
    else
        echo "INFO: SS_MODULE is ${SS_MODULE}, not run privoxy!"
		exit 0
    fi
else
    exit 0
fi


