#!/bin/bash

exec 2>&1

if [ -z "${SS_MODULE}" ]; then
    SS_MODULE="ss-server"
fi

if [ "${SS_MODULE}" == "ss-local" ]; then
    echo "starting polipo..."
	if [ -n "${POLIPO_CONFIG}" ]; then
	    exec chpst -u polipo polipo ${POLIPO_CONFIG}
	else
	    exec chpst -u polipo polipo -c /etc/polipo.conf
	fi
	exit 0
else
    echo "INFO: SS_MODULE is ${SS_MODULE}, exit!"
    exit 0
fi
