#!/bin/bash

exec 2>&1

if [ -z "${SS_MODULE}" ]; then
    SS_MODULE="ss-server"
fi

if [ "${SS_MODULE}"="ss-local" ]; then
    echo "starting squid..."
    exec chpst -u squid squid
else
    echo "Error: SS_CONFIG is empty, exit!"
    exit 1
fi
