#!/bin/bash

exec 2>&1

if [ "${SQUID_FLAG}" == "true" ]; then
	if [ -z "${SS_MODULE}" ]; then
		SS_MODULE="ss-server"
	fi

	if [ "${SS_MODULE}" == "ss-local" ]; then
		echo "starting squid..."
		exec chpst -u squid squid
	else
		echo "Error: SS_CONFIG is empty, exit!"
		exit 1
	fi
else
    exit 0
fi
