#!/bin/bash

exec 2>&1

if [ "${P_LOCAL_FLAG}" == "true" ]; then
    if [ "${SS_MODULE}" == "ss-local" ]; then
        echo "starting privoxy local..."
	    exec privoxy --no-daemon /etc/privoxy-local-only/config
    else
        echo "INFO: SS_MODULE is ${SS_MODULE}, not run privoxy!"
		exit 0
    fi
else
    exit 0
fi


